---
- hosts: all
  become: true
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: "install python"
      raw: "sudo apt-get -y install python"
  roles:
    - prepare
    - k8s-dep

- hosts: kubernetes_master
  become: true
  remote_user: root
  gather_facts: no
  roles:
    - master

- hosts: kubernetes_workers
  become: true
  remote_user: root
  gather_facts: no
  roles:
    - worker