---
- name: "remove old docker"
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent
  notify:
    - refresh_apt_cache

- name: "ensure docker dependencies"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: "install docker apt key"
  apt_key:
    url: "{{ docker.apt_key }}"
    state: present

- name: "add docker apt repository"
  apt_repository:
    repo: "{{ docker.apt_repo }}"
    state: present
  notify:
    - refresh_apt_cache

- name: "ensure docker"
  apt:
    name:
      - docker-ce
    state: present
