---
- name: "add yq repository"
  apt_repository:
    repo: "{{ yq.apt_repo }}"
    state: present

- name: "refresh_apt_cache"
  apt:
    update_cache: yes

- name: "ensure yq executables"
  apt:
    name:
      - yq
    state: present
